### PR TITLE
Add table of content inside navigation

### PR DESCRIPTION
**Pull request by TheRolfFR**
hello,

This PR is made to solve #20.

I finished the work on the table of content for the table of content inside the navigation, i used the posts json loader in order to extract html element when browsing posts.

I can now have all the table of contents for all the articles. 
I first made the table of content for all articles but realized we have some navigation problems due to the page loading then scrolling, and it wasn't really smooth.

I then changed to only show active article table of content.

Colors, font sizes and icons can still be adjusted. 

All discussion details should be here for centralized discussion.

Screenshots:
image

### CODE REVIEW

**Comment by 3vorp** [comment]
I really like this, but I'd like to request a few smaller changes:

- the ability to collapse the table of contents without collapsing the entire category
- increase the padding between each row
- add a bit more "hierarchy" by making the table of contents background a bit darker than the header, so they don't look like they're on the same level (the linux kernel docs do this really well, it's really easy to see when an article is closed or opened and the difference between each level thanks to the dynamic background colors)

**Comment by 3vorp** [comment]
oh also here's a random idea — dark sidebar with a light main background text when you're in light mode, similar to how Discord themes its light mode UI

Screen Shot 2023-05-30 at 7 59 31 AM

I feel like most good light modes tend to have some sort of accent color or contrast color and this looks a _lot_ better than the current blinding white everywhere imo

if people disagree with this then I'm fine with dropping the idea but I think it looks good personally so I'd suggest not changing the navbar with light mode and just using the dark mode one for both

**Comment by 3vorp** [comment]
oh also I didn't notice this initially but — can we only show top level elements by default unless you click on them to see their subcategories

so like only h1 elements and titles would be shown unless you click on a given section and it expands into the subpoints (using the linux kernel docs as an example here again)

Screen Shot 2023-05-30 at 5 00 12 PM

I think that showing everything all at once is just too much information and also pushes the navbar really far down, but showing only the relevant type of content at a given point in time ensures that there's only like ten subheadings max and nothing gets pushed down too far

**Comment by TheRolfFR** [comment]
Okay, got new content and table of content only if current page, looks better, checkout and launch if desired.
Little gif to present style changes 😍:
restyle_and_nav

**Review by RobertRR11 — APPROVED** [review]

**Pull request merged**
